### ISSUE TITLE
LavaLauncher does not react to mouse input

### ISSUE THREAD

**Issue by RicArch97** [Leon-Plickat/LavaLauncher#5] opened 2021-04-16 15:54 UTC
Hovering over the bar with the mouse pointer does not show the indicator, also clicking on the buttons does nothing. The bar does display correctly however.

It looks like a layer issue.

Config here:
```
bar 
{
        # Bar on right monitor
        output                  =DP-1;
        size                    =52;
        position                =left;
        margin                  =10;
        border                  =0;
        background-colour       ="#00000000";
        alignment               =center;
        exclusive-zone          =false;
        indicator-style         =circle;

        config
        {       
                output          =DP-2;
                icon-padding    =8;
        }

        button 
        {       
                image-path      =/usr/share/icons/McMojave-circle-grey-dark/apps/scalable/vscode.svg;
                command         =code;
        }

        spacer 
        {
                length          =4;
        }

        <more buttons and spacers here>
}
```

I've tried running with:
* Exclusive zone `true`, `false` and `stationary` respectively
* Layer `top`, `overlay`, `bottom` `background` respectively

But same result with all those options (individually).
I even tried with different mouse pointers, same result.

Running Sway 1.6 (community package) with wlroots 0.13.0.

**Comment by Leon-Plickat** [comment] 2021-04-16 17:08
Can you try replacing one of the `command`s with
`command[mouse-left]`?

I have a suspicion.


Friendly greetings,
Leon Plickat

**Comment by RicArch97** [comment] 2021-04-16 17:30
That did the trick.

But i only needed to change it for one of the `command`'s indeed. Changing one makes all of the other functional again .

so changing `command` to `command[mouse-left]` for one button, makes all other buttons functional again which still have `command`

**Comment by Leon-Plickat** [comment] 2021-04-16 18:22
Damn, that should  not happen. In fact, we had that bug once already
but it was fixed. I'll investigate shortly.


Friendly greetings,
Leon Plickat

**Comment by RicArch97** [comment] 2021-04-16 18:43
Thanks for the quick responses Leon!

**Comment by Leon-Plickat** [comment] 2021-04-17 12:23
What version are you on? Are you on version 2.1.0 or an earlier commit? Because version 2.1.0 definitely has the fix for this. To be more precise the commit containing the fix is 809b19b148dc4e4a1591be1bae57d68c2cb519f3. I don't know how you installed lavalauncher, but I am pretty sure you installed a commit somewhere between configuration sets being introduced and the fix being merged.

**Comment by RicArch97** [comment] 2021-04-17 14:30
I have installed `lavalauncher 2.1.0-2` from the AUR.

`lavalauncher -V` returns: LavaLauncher version GIT-9519d0b (Apr 16 2021, branch 'master')

**Comment by Leon-Plickat** [comment] 2021-04-17 16:39
Weird. The AUR package does not clone the git repo but downloads a
tarball. If the source at compile time is not in a git repository,
then the version string returned by `lavalauncher --version` should
not be a git commit hash. Also commit 9519d0b does not appear to
exist? I had to force-push once or twice to master, maybe it is an
old overwritten one. Can you tell me what the description says?

Have you maybe installed LavaLauncher once manually and put the
binary into a directory that with a higher path priority than
`/usr/{local/}share/bin`?



Friendly greetings,
Leon Plickat

**Comment by RicArch97** [comment] 2021-04-17 17:10
My current system is actually a completely fresh install, which was done yesterday, because I've upgraded some hardware and wanted to start clean. The only version that was ever on here is the one from the AUR.

**Comment by Leon-Plickat** [comment] 2021-04-17 17:21
On Sat Apr 17, 2021 at 7:10 PM CEST, Ricardo Steijn wrote:
> My current system is actually a completely fresh install, which was done
> yesterday, because I've upgraded some hardware and wanted to start
> clean. The only version that was ever on here is the one from the AUR.

Turns out the build system picks up the git repository of the AUR
package when building, so the commit hash is from that. That's
annoying.

I can reproduce the issue now. Thing is: I should not be able to
run that version of LavaLauncher at all on this device, as on
this laptop I still run Sway 1.5 which does not support the
new layershell version LavaLauncher uses in 2.1.0. This means that
whatever is build through the AUR package is definitely not version
2.1.0.

I'll investigate this and get back to you once I have found out
what the issue is. For now if you'd like to use LavaLauncher 2.1.0
you need to build from source manually:

    git clone ***@***.***:~leon_plickat/lavalauncher
    cd lavalauncher
    git checkout v2.1.0
    meson build
    ninja -C build
    sudo ninja -C build install



Friendly greetings,
Leon Plickat

**Comment by Leon-Plickat** [comment] 2021-04-17 17:31
Actually, scratch my earlier mail, the AUR package does indeed download the correct source. The problem is that the fix never actually fixed anything, because it added code after a `return`. Apparently neither I nor the contributor ever tested that? Slightly embarrassing...

Anyway, I'll push  a real fix to master in a few minutes. If no new bugs are reported within a week or two I'll release 2.1.1 including this fix.

Regarding the phaantom comment hash: The build system picks up the git repository of the AUR package and uses its commit hash. Pretty annoying. I might have to change the version string manually for future releases.

**Comment by Leon-Plickat** [comment] 2021-04-17 17:40
Pushed the fix. If you want it, you'll have to build from source manually for now.

**Comment by RicArch97** [comment] 2021-04-17 18:50
Thanks for the quick fix!

I'll dive into the source when i have some more time so can i potentially get to issues quicker or contribute

**Comment by Leon-Plickat** [comment] 2021-04-17 19:07
On Sat Apr 17, 2021 at 8:50 PM CEST, Ricardo Steijn wrote:
> Thanks for the quick fix!
>
> I'll dive into the source when i have some more time so can i
> potentially get to issues quicker or contribute

Then check out the lavalauncher-next branch, development for the version
3.0.0 happens there.


Friendly greetings,
Leon Plickat

**Closed** 2021-04-17 19:47 UTC
